version: '3'
services:

  api:
    build: ./api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${API_PORT}:8000

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=http://localhost:${API_PORT}
    ports:
      - ${FRONT_PORT}:3000
